<?php
/**
 * Phase F.2 — regenerate the parent-contract baseline file.
 *
 * Reads the canonical list of (file, start_line, end_line, note) tuples
 * from this script, hashes each against the current parent source, and
 * writes tests/parent-contract.baseline.json.
 *
 * Run this when the parent plugin updates and the watcher fails — but ONLY
 * after manually auditing the diff to confirm the parent's contract is
 * still compatible with the companion. A blind baseline refresh defeats
 * the watcher's purpose.
 *
 * Usage:
 *   DFWC_PARENT_PATH=/path/to/donation-for-woocommerce php tests/parent-contract.update-baseline.php
 *
 * @package   DFWC\Companion
 * @copyright Copyright (c) 2026 David Stells
 * @license   GPL-2.0-or-later https://www.gnu.org/licenses/gpl-2.0.html
 */

declare(strict_types=1);

if ( PHP_SAPI !== 'cli' ) {
	fwrite( STDERR, "This script must be run from the CLI.\n" );
	exit( 2 );
}

/**
 * The line ranges the companion depends on. Update this list when adding
 * new dependencies on parent source. Each tuple = [ relative_path, start,
 * end, why-it-matters ].
 */
$RANGES = [
	[ 'includes/classes/class-wcdonationorder.php',          1540, 1820, 'AJAX handler add_donation_to_order_action — the contract our submit feeds' ],
	[ 'includes/classes/class-wcdonationorder.php',          1655, 1655, 'RecurringDisp === user gate (D1 origin)' ],
	[ 'includes/classes/class-wcdonationcampaignsetting.php', 614,  630, 'Single-page form render + before/after action hooks (D3 wraps these)' ],
	[ 'includes/classes/class-wcdonationcampaignsetting.php', 920,  935, 'Shortcode form render + before/after action hooks (D3 wraps these)' ],
	[ 'includes/classes/class-wcdonationcampaignsetting.php', 1820, 1840, 'wc_donation_after_save_campaign_meta action — our save handler hooks here' ],
	[ 'includes/classes/class-wcdonationproces.php',          324,  355, 'Frontend localize block — reference for our own dfwcCompanion localize shape' ],
	[ 'includes/classes/class-wcdonationsubscriptionfree.php',  78,  110, 'WPS SFW expiry handling — open-ended convention (empty expiry fields)' ],
];

$parent_path = rtrim( getenv( 'DFWC_PARENT_PATH' ) ?: ( __DIR__ . '/donation-for-woocommerce' ), '/\\' );
if ( ! is_dir( $parent_path ) ) {
	fwrite( STDERR, "ERROR: parent plugin path not found: {$parent_path}\n" );
	fwrite( STDERR, "Set DFWC_PARENT_PATH to the donation-for-woocommerce directory.\n" );
	exit( 2 );
}

$out = [
	'_comment'       => 'Auto-generated by tests/parent-contract.update-baseline.php. Do not edit by hand.',
	'parent_version' => detect_parent_version( $parent_path ),
	'generated_at'   => gmdate( 'Y-m-d\TH:i:s\Z' ),
	'ranges'         => [],
];

foreach ( $RANGES as $range ) {
	[ $rel, $start, $end, $note ] = $range;
	$abs = $parent_path . DIRECTORY_SEPARATOR . $rel;
	if ( ! is_file( $abs ) ) {
		fwrite( STDERR, "WARN  {$rel}: file missing — entry skipped\n" );
		continue;
	}
	$out['ranges'][] = [
		'file'   => $rel,
		'start'  => $start,
		'end'    => $end,
		'sha256' => sha256_of_lines( $abs, $start, $end ),
		'note'   => $note,
	];
	fwrite( STDOUT, "HASH  {$rel}:{$start}-{$end}\n" );
}

$baseline_path = __DIR__ . '/parent-contract.baseline.json';
file_put_contents( $baseline_path, json_encode( $out, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) . "\n" );
fwrite( STDOUT, "\nWrote {$baseline_path}\n" );

function sha256_of_lines( string $path, int $start, int $end ): string {
	$lines = file( $path, FILE_IGNORE_NEW_LINES );
	if ( ! is_array( $lines ) ) {
		return '';
	}
	$slice = array_slice( $lines, max( 0, $start - 1 ), max( 0, $end - $start + 1 ) );
	return hash( 'sha256', implode( "\n", $slice ) );
}

function detect_parent_version( string $parent_path ): string {
	$main = $parent_path . '/class-wcdonation.php';
	if ( ! is_file( $main ) ) {
		return '';
	}
	$head = file_get_contents( $main, false, null, 0, 4096 ) ?: '';
	if ( preg_match( '/^\s*\*\s*Version:\s*(\S+)/mi', $head, $m ) ) {
		return $m[1];
	}
	return '';
}
